const number1 = 3;
const number2 = 8;
const product = number1 * number2;
console.log(product);
console.log(typeof product);
const charge = 100;
const payment = 25;
const amountRemaining = charge - payment;
console.log(amountRemaining);
console.log(typeof amountRemaining);
const tests = 3;
const assignments = 20;
const final = 1;
const grade = (tests + assignments + final) / 3;
console.log(grade);
console.log(typeof grade);
const firstName = 'Connie';
const lastName = 'Chin';
const fullName = firstName + ' ' + lastName;
console.log(fullName);
console.log(typeof fullName);
const pH = 9;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const numberOfSoldiers = 150;
const isSparta = numberOfSoldiers === 300;
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName + ' is the GOAT';
console.log(nickname);
console.log(typeof nickname);
